export const CONFIRMATION = 'CONFIRMATION';
export const EXTRAS_SELECTION = 'EXTRAS_SELECTION';
export const LOADING = 'LOADING';
export const PAYMENT = 'PAYMENT';
export const PERSONAL_INFORMATION = 'PERSONAL_INFORMATION';
export const RECAP = 'RECAP';
export const TRIP_SELECTION = 'TRIP_SELECTION';
export const UNINITIALIZED = 'UNINITIALIZED';
